server:
  port: 8888

spring:
  application:
    name: b2b-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info
